### ISSUE TITLE
Languages have different plural rules

### ISSUE THREAD

**Issue by ameshkov** [NickStrupat/TimeAgo#5]
Current implementation uses the same rule for all languages.

In english this rule is pretty simple:
1 second
N seconds

In russian, for instance, it is different:
1 секунд**а**
2 секунд**ы**
5 секунд

Read more about it here:
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#Polish

**Comment by NickStrupat** [comment]
I'm working on a wrapper which invokes Moment.js which has great support for many languages. Likely will call it FromNow since it also supports dates in the future (e.g. "in 4 days").

**Comment by ameshkov** [comment]
Don't you think embedding a JS engine is an overkill?

**Comment by ameshkov** [comment]
JFYI, pretty nice library taking care of these rules:
https://github.com/Humanizr/Humanizer#humanize-timespan

**Comment by NickStrupat** [comment]
Wow, yep, never saw that library...

The JS wrapper is actually part of a more general project I'm working on. I'm trying to take TypeScript definition files and generate .NET wrappers. The end goal being to expose basically anything with a TypeScript definition to .NET without having to evaluate strings of code and such. Also intellisense :)

I figured I'd start with wrapping Moment.js to learn about the various JS engines/interops for .NET.

**Comment by ameshkov** [comment]
Got it. I hope you'll use a JS engine which is used by some browser, therefore compatible with all popular js libraries.

Here are some engines I know about, just in case.

https://github.com/JavascriptNet/Javascript.Net
A V8 wrapper, tried it and it works good. Not sure about memory footprint though.

https://github.com/Microsoft/ChakraCore
MS Edge browser javascript engine. I've not yet tried it, but I'd like to see how good is it:)

**Comment by NickStrupat** [comment]
I was hoping to use EdgeJS since it wraps Node and therefore V8, and intends to support .NET Core. But, I've been having problems with running the example snippets, particularly starting a node http server.

Anyway, I'll keep working on it. Mostly I'm still working on the JS code which call the TypeScript compiler API so I can walk the AST of the definition files.

**Comment by NickStrupat** [comment]
Just realizing that once Node has official support for ChakraCore, Edge should be able to run on ChakraCore with no problems :)

**Comment by ameshkov** [comment]
Depends on the ChakraCore lobby:) However I don't fully understand why do you need Node support for this thing.

Basically, all JS engines are alike. You can make an abstraction layer and then use whatever engine you like to implement it:

```
interface IJavascriptEngine 
{
    string RunScript(string scriptText);
    event EventHandler JavascriptEvent;
}
```

**Comment by NickStrupat** [comment]
I definitely don't need Node support for it, it's just the JS interop library I went with for my prototype. I was planning to use some libraries which use Node in another project of mine. Ideally, my tool will allow for whatever JS interop library the user wants.

Hmm, an implementation of IJavascriptEngine might be necessary.
