### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by michaelvlaar** [NickStrupat/TimeAgo#7]
Hi,

Is it possible to add UWP support for this package?

Thanks,
Michael

**Comment by NickStrupat** [comment]
Hi Michael,

Thanks for that pull request. I've decided to abandon development on this project. There is a better equivalent called Humanizer at https://github.com/Humanizr/Humanizer. I'm pretty sure they already target UWP. I recommend using that, for what it's worth.
